export const USER_API_BASE_URL='http://127.0.0.1:6800';
export const SAVE_USER_API_ROUTE=`${USER_API_BASE_URL}/users`;
export const GET_USER_API_ROUTE=SAVE_USER_API_ROUTE;
export const REMOVE_USER_API_ROUTE=SAVE_USER_API_ROUTE;